apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - clickhouse-operator.yaml
  - external-dns.yaml
  - flux-system.yaml
  - gateway-api.yaml
  - grafana.yaml
  - istio-base.yaml
