apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kustomizations
  - crd-controller.yaml
  - gitrepository.yaml
  - helm-controller.yaml
  - helmrepositories.yaml
  - kustomize-controller.yaml
  - namespace.yaml
  - source-controller.yaml
