env:
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: dns://otel-collector.otel.svc.cluster.local:4317
  - name: OTEL_LOGS_EXPORTER
    value: otlp
  - name: OTEL_METRICS_EXPORTER
    value: none
  - name: OTEL_TRACES_EXPORTER
    value: none
