apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rules
  - namespace.yaml
  - vlalert.yaml
  - vlcluster.yaml
  - vmagent.yaml
  - vmalert.yaml
  - vmalertmanager.yaml
  - vmcluster.yaml
  - vmoperator.yaml
  - vtcluster.yaml
