apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana/dashboards
  - grafana/datasources
  - grafana/folders
  - grafana/users
  - clickhouse.yaml
  - grafana-operator.yaml
  - grafana.yaml
  - kiali.yaml
  - namespace.yaml
  - otel-collector-agent.yaml
  - prometheus.yaml
