---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager.yaml
  - clickhouse-observability.yaml
  - istio.yaml
  - kubernetes.yaml
  - prometheus.yaml
  - victorialogs.yaml
  - victoriametrics.yaml
  - victoriatraces.yaml
