---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clickhouse-operator
  namespace: flux-system
spec:
  interval: 15m
  path: ./homelab/kubernetes/clickhouse-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: playground
  dependsOn:
    - name: base
