---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability
  namespace: flux-system
spec:
  interval: 15m
  path: ./homelab/kubernetes/observability
  prune: true
  sourceRef:
    kind: GitRepository
    name: playground
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  dependsOn:
    - name: base
