---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: bookinfo
  namespace: observability
spec:
  allowCrossNamespaceImport: true
  instanceSelector: {}
  uid: bookinfo
  title: bookinfo
