---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: clickhouse-operator
  namespace: observability
spec:
  allowCrossNamespaceImport: true
  instanceSelector: {}
  uid: clickhouse-operator
  title: clickhouse-operator
