---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: flux-system
  namespace: observability
spec:
  allowCrossNamespaceImport: true
  instanceSelector: {}
  uid: flux-system
  title: flux-system
