---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: istio-system
  namespace: observability
spec:
  allowCrossNamespaceImport: true
  instanceSelector: {}
  uid: istio-system
  title: istio-system
