---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: otel-demo
  namespace: observability
spec:
  allowCrossNamespaceImport: true
  instanceSelector: {}
  uid: otel-demo
  title: otel-demo
