---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: victoriastack
  namespace: observability
spec:
  allowCrossNamespaceImport: true
  instanceSelector: {}
  uid: victoriastack
  title: victoriastack
