---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: echoserver
  namespace: echoserver
spec:
  releaseName: echoserver
  chart:
    spec:
      chart: echoserver
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: ricoberger
        namespace: flux-system
  driftDetection:
    mode: enabled
  install:
    crds: Skip
  upgrade:
    crds: Skip
  interval: 15m
  timeout: 10m
  values:
    podLabels:
      app: echoserver

    resources:
      limits:
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 64Mi

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsGroup: 65534
      runAsNonRoot: true
      runAsUser: 65534
      seccompProfile:
        type: RuntimeDefault

    service:
      labels:
        app: echoserver

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: echoserver

    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector-agent.observability.svc.cluster.local:4317
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_METRICS_EXPORTER
        value: otlp
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: service.namespace=echoserver

---
# curl -o /dev/null -s -w 'Total: %{time_total}s | Status: %{http_code}\n' 'https://echoserver-http.homelab.ricoberger.dev/status?status=random'
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echoserver
  namespace: echoserver
spec:
  parentRefs:
    - name: istio-ingress
      namespace: istio-ingress
  hostnames:
    - "echoserver-http.homelab.ricoberger.dev"
  rules:
    - backendRefs:
        - name: echoserver
          port: 8080

---
# grpcurl -format-error -authority echoserver-grpc.homelab.ricoberger.dev -d '{ "status": "random" }' echoserver-grpc.homelab.ricoberger.dev:443 Echoserver.Status
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: echoserver
  namespace: echoserver
spec:
  parentRefs:
    - name: istio-ingress
      namespace: istio-ingress
  hostnames:
    - "echoserver-grpc.homelab.ricoberger.dev"
  rules:
    - backendRefs:
        - name: echoserver
          port: 8081

---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: echoserver-http
  namespace: echoserver
spec:
  endpoints:
    - dnsName: echoserver-http.homelab.ricoberger.dev
      recordTTL: 300
      recordType: A
      targets:
        - 192.168.2.143

---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: echoserver-grpc
  namespace: echoserver
spec:
  endpoints:
    - dnsName: echoserver-grpc.homelab.ricoberger.dev
      recordTTL: 300
      recordType: A
      targets:
        - 192.168.2.143
