dist:
  name: otel-collector
  version: 0.138.0
  output_path: .

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.138.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension
      v0.138.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage
      v0.138.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.138.0
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.138.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.138.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.138.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhouseexporter
      v0.138.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.138.0
  - gomod:
      go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.138.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor
      v0.138.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor
      v0.138.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/geoipprocessor
      v0.138.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor
      v0.138.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor
      v0.138.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor
      v0.138.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/nopreceiver v0.138.0
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.138.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver
      v0.138.0

connectors:
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/connector/otlpjsonconnector
      v0.138.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.44.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.44.0
